# Generated by Django 2.2.3 on 2019-07-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='cep',
            field=models.CharField(default='60821655', max_length=20, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='pais',
            field=models.CharField(default='Brasil', max_length=60, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='lat',
            field=models.CharField(max_length=50, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='lon',
            field=models.CharField(max_length=50, verbose_name='Longitude'),
        ),
    ]
